# Generated by Django 3.2.3 on 2023-08-02 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Нужно указать нормальное количество!')], verbose_name='Количество в рецепте'),
        ),
    ]
